-- 20260528000010_gstt_canonical_36_act_backfill_fix.sql
-- Sửa hanh_dong_khac_phuc_jsonb cho 4 mẫu (000009 parse ACT sai do markdown escape)
begin;

-- BM.10.01
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"* [ ] Cảnh báo và yêu cầu NVYT dừng ngay mọi thao tác chăm sóc/điều trị đối với NB hiện tại để xử lý vết thương.","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"* [ ] Can thiệp lập tức nếu phát hiện NVYT đang nặn/bóp máu. Hướng dẫn NVYT xả trực tiếp vết thương dưới vòi nước chảy.","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"* [ ] Cung cấp ngay dung dịch NaCl 0.9% để rửa mắt/niêm mạc (Nếu là tai nạn văng bắn dịch).","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"* [ ] Hỗ trợ NVYT gọi ngay số điện thoại Hotline Khoa Truyền nhiễm/KSNK để nhận tư vấn và điều trị dự phòng PEP (ARV/HBIg) trong \"giờ vàng\".","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"* [ ] Phân công NVYT khác trong ca trực tiếp tục thực hiện phần công việc đang dang dở của nhân viên bị phơi nhiễm.","action_code":"ACT-200","la_stop_the_line":false},{"stt":6,"noi_dung":"* [ ] Hướng dẫn Điều dưỡng trưởng khoa/NVYT hoàn thành \"Biên bản báo cáo tai nạn rủi ro nghề nghiệp\" (BM.10.01).","action_code":"ACT-500","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.10.01';

-- BM.QĐ.19.03
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"* [ ] Đình chỉ và Tịch thu: Tịch thu ngay lập tức các vật tư/dụng cụ đã hết hạn, rách bao bì, hoặc bị ướt. Dán nhãn đỏ \"HẾT HẠN/HỎNG\" và chuyển về bộ phận hậu cần/CSSD.","action_code":"ACT-400","la_stop_the_line":true},{"stt":2,"noi_dung":"* [ ] Yêu cầu loại bỏ ngay vào thùng rác các vật tư dùng 1 lần đã được mang vào buồng bệnh/khu cách ly nhưng chưa dùng đến (Tuyệt đối không hoàn kho).","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"* [ ] Kích hoạt quy trình thu hồi (Recall) và báo cáo sự cố y khoa nếu phát hiện vật tư quá hạn/hỏng đã được sử dụng trên cơ thể người bệnh.","action_code":"ACT-500","la_stop_the_line":false},{"stt":4,"noi_dung":"* [ ] Yêu cầu nhân viên CSSD hủy bỏ ngay lập tức các SUDs không có tên trong danh mục được phê duyệt hoặc đã vượt quá số lần tái sử dụng cho phép.","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"* [ ] Yêu cầu Điều dưỡng trưởng sắp xếp lại tủ vật tư theo nguyên tắc FEFO/FIFO ngay trong ca trực.","action_code":"ACT-200","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.QĐ.19.03';

-- BM.27.02
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"* [ ] Cảnh báo và yêu cầu treo ngay túi dẫn lưu THẤP HƠN bàng quang và móc cố định vào khung giường nếu phát hiện túi đang để trên bụng NB hoặc nằm dưới sàn nhà [2, 5].","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"* [ ] Yêu cầu Điều dưỡng/Hộ lý xả ngay túi nước tiểu nếu quan sát thấy túi đã đầy trên 2/3; hướng dẫn lại tại chỗ việc không để vòi xả chạm thành bình hứng [2, 6].","action_code":"ACT-100","la_stop_the_line":false},{"stt":3,"noi_dung":"* [ ] Cung cấp ngay bình đong nước tiểu sạch, có dán tên/số giường riêng biệt cho NB nếu phát hiện điều dưỡng đang sử dụng chung một bình hứng cho nhiều giường [2, 4, 6].","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"* [ ] Đình chỉ thao tác và nhắc nhở nghiêm khắc nếu phát hiện Điều dưỡng cố tình tháo rời chốt nối giữa ống thông và dây dẫn (phá vỡ hệ thống kín) để lấy nước tiểu hoặc thay quần áo [2, 3, 6].","action_code":"ACT-400","la_stop_the_line":true},{"stt":5,"noi_dung":"* [ ] Phản hồi trực tiếp yêu cầu Bác sĩ ghi bổ sung y lệnh đánh giá Rút hoặc Tiếp tục lưu ống thông tiểu vào hồ sơ bệnh án của ngày hiện tại [2, 3, 6].","action_code":"ACT-200","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.27.02';

-- BM.QĐ.20.01
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"* [ ] Đình chỉ hệ thống ngay lập tức: Dừng vận hành hệ thống lọc máu RO và báo kỹ sư nếu test nhanh phát hiện nồng độ Clo dư \\> 0.1 mg/L hoặc độ cứng vượt ngưỡng an toàn.","action_code":"ACT-400","la_stop_the_line":true},{"stt":2,"noi_dung":"* [ ] Đình chỉ thao tác phẫu thuật nha khoa, yêu cầu Bác sĩ chuyển ngay sang sử dụng nước muối sinh lý vô khuẩn và bơm tiêm/dây dẫn rời nếu phát hiện đang dùng nước từ ghế nha để xịt rửa ổ răng phẫu thuật.","action_code":"ACT-400","la_stop_the_line":true},{"stt":3,"noi_dung":"* [ ] Nhắc nhở và yêu cầu Điều dưỡng/Bác sĩ nha khoa thực hiện bấm xả đường ống tay khoan và vòi xịt đủ 20 \\- 30 giây ngay lập tức trước khi mời người bệnh tiếp theo lên ghế.","action_code":"ACT-100","la_stop_the_line":false},{"stt":4,"noi_dung":"* [ ] Yêu cầu thực hiện quy trình khử khuẩn sốc (Shock treatment) cho đường ống ghế nha hoặc sục rửa hệ thống RO, sau đó tiến hành lấy mẫu nước xét nghiệm lại nếu kết quả vi sinh tháng trước báo Không Đạt.","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"* [ ] Yêu cầu Kỹ sư/Điều dưỡng hoàn thiện ngay việc ghi chép và ký xác nhận vào Nhật ký theo dõi chất lượng nước nếu phát hiện bỏ sót sổ sách đầu ngày.","action_code":"ACT-200","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.QĐ.20.01';

commit;