-- Pilot RBAC seed — generated by scripts/generate-pilot-seeds.ts
-- Idempotent: safe to re-run after supabase db reset --local

BEGIN;

INSERT INTO public.sys_roles (name, description, is_active)
VALUES
  ('ADMIN', 'Quản trị hệ thống (Root)', true),
  ('NHAN_VIEN_KSNK', 'Nhân viên khoa Kiểm soát nhiễm khuẩn', true),
  ('HOI_DONG_KSNK', 'Hội đồng KSNK — chủ yếu xem báo cáo', true),
  ('MANG_LUOI_KSNK', 'Mạng lưới KSNK (vai trò hệ thống)', true),
  ('TO_TRUONG_MANG_LUOI_KSNK', 'Tổ trưởng tổ mạng lưới KSNK theo khoa', true),
  ('THANH_VIEN_MANG_LUOI_KSNK', 'Thành viên mạng lưới KSNK theo khoa', true),
  ('BAN_QLCL', 'Ban Quản lý Chất lượng Bệnh viện — tiếp nhận ticket RCA hệ thống', true),
  ('KHOA_TRANG_BI', 'Khoa Trang bị — tiếp nhận ticket RCA về thiết bị/nguồn lực', true)
ON CONFLICT (name) DO UPDATE SET
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active,
  updated_at = now();

INSERT INTO public.sys_permissions (module_name, action, description)
VALUES
  ('DASHBOARD', 'view', 'Xem Command Center — quyền tổng (tương thích trước khi tách widget)'),
  ('DASHBOARD_CC_OVERVIEW', 'view', 'Xem Command Center — Tab Cơ cấu nguồn & tổng hợp'),
  ('DASHBOARD_CC_SUPERVISION', 'view', 'Xem Command Center — Tab Chuyên trách / Chéo / Tự giám sát'),
  ('DASHBOARD_CC_GAP', 'view', 'Xem Command Center — Tab Đối soát & Lệch'),
  ('DASHBOARD_CC_EXPORT', 'export', 'Xuất dữ liệu Command Center — Xuất / in báo cáo PDF'),
  ('DANH_MUC', 'view', 'Xem Quản trị Danh mục'),
  ('DANH_MUC', 'create', 'Thêm Quản trị Danh mục'),
  ('DANH_MUC', 'edit', 'Sửa Quản trị Danh mục'),
  ('DANH_MUC', 'delete', 'Xóa Quản trị Danh mục'),
  ('DANH_MUC', 'import', 'Import Quản trị Danh mục'),
  ('NHAN_SU', 'view', 'Xem Quản lý Nhân sự'),
  ('NHAN_SU', 'create', 'Thêm Quản lý Nhân sự'),
  ('NHAN_SU', 'edit', 'Sửa Quản lý Nhân sự'),
  ('NHAN_SU', 'delete', 'Xóa Quản lý Nhân sự'),
  ('NHAN_SU', 'import', 'Import Quản lý Nhân sự'),
  ('BANG_KIEM', 'view', 'Xem Danh mục Bảng kiểm'),
  ('BANG_KIEM', 'create', 'Thêm Danh mục Bảng kiểm'),
  ('BANG_KIEM', 'edit', 'Sửa Danh mục Bảng kiểm'),
  ('BANG_KIEM', 'delete', 'Xóa Danh mục Bảng kiểm'),
  ('BANG_KIEM', 'import', 'Import Danh mục Bảng kiểm'),
  ('CONG_VIEC', 'view', 'Xem Quản lý Công việc'),
  ('CONG_VIEC', 'create', 'Thêm Quản lý Công việc'),
  ('CONG_VIEC', 'edit', 'Sửa Quản lý Công việc'),
  ('CONG_VIEC', 'delete', 'Xóa Quản lý Công việc'),
  ('CONG_VIEC', 'import', 'Import Quản lý Công việc'),
  ('CONG_VIEC', 'approve', 'APPROVE Quản lý Công việc'),
  ('LOAI_DC', 'view', 'Xem Danh mục Loại dụng cụ'),
  ('LOAI_DC', 'create', 'Thêm Danh mục Loại dụng cụ'),
  ('LOAI_DC', 'edit', 'Sửa Danh mục Loại dụng cụ'),
  ('LOAI_DC', 'delete', 'Xóa Danh mục Loại dụng cụ'),
  ('LOAI_DC', 'import', 'Import Danh mục Loại dụng cụ'),
  ('BO_DC', 'view', 'Xem Danh mục Bộ dụng cụ'),
  ('BO_DC', 'create', 'Thêm Danh mục Bộ dụng cụ'),
  ('BO_DC', 'edit', 'Sửa Danh mục Bộ dụng cụ'),
  ('BO_DC', 'delete', 'Xóa Danh mục Bộ dụng cụ'),
  ('BO_DC', 'import', 'Import Danh mục Bộ dụng cụ'),
  ('DC_LE', 'view', 'Xem Danh mục Dụng cụ chi tiết'),
  ('DC_LE', 'create', 'Thêm Danh mục Dụng cụ chi tiết'),
  ('DC_LE', 'edit', 'Sửa Danh mục Dụng cụ chi tiết'),
  ('DC_LE', 'delete', 'Xóa Danh mục Dụng cụ chi tiết'),
  ('DC_LE', 'import', 'Import Danh mục Dụng cụ chi tiết'),
  ('THIET_BI', 'view', 'Xem Danh mục Thiết bị'),
  ('THIET_BI', 'create', 'Thêm Danh mục Thiết bị'),
  ('THIET_BI', 'edit', 'Sửa Danh mục Thiết bị'),
  ('THIET_BI', 'delete', 'Xóa Danh mục Thiết bị'),
  ('THIET_BI', 'import', 'Import Danh mục Thiết bị'),
  ('HOA_CHAT', 'view', 'Xem Danh mục Hóa chất'),
  ('HOA_CHAT', 'create', 'Thêm Danh mục Hóa chất'),
  ('HOA_CHAT', 'edit', 'Sửa Danh mục Hóa chất'),
  ('HOA_CHAT', 'delete', 'Xóa Danh mục Hóa chất'),
  ('HOA_CHAT', 'import', 'Import Danh mục Hóa chất'),
  ('KHOA_PHONG', 'view', 'Xem Danh mục Khoa phòng'),
  ('KHOA_PHONG', 'create', 'Thêm Danh mục Khoa phòng'),
  ('KHOA_PHONG', 'edit', 'Sửa Danh mục Khoa phòng'),
  ('KHOA_PHONG', 'delete', 'Xóa Danh mục Khoa phòng'),
  ('KHOA_PHONG', 'import', 'Import Danh mục Khoa phòng'),
  ('BANG_KIEM_DETAIL', 'view', 'Xem Tiêu chí Bảng kiểm'),
  ('BANG_KIEM_DETAIL', 'create', 'Thêm Tiêu chí Bảng kiểm'),
  ('BANG_KIEM_DETAIL', 'edit', 'Sửa Tiêu chí Bảng kiểm'),
  ('BANG_KIEM_DETAIL', 'delete', 'Xóa Tiêu chí Bảng kiểm'),
  ('BANG_KIEM_DETAIL', 'import', 'Import Tiêu chí Bảng kiểm'),
  ('CSSD_REPORT', 'view', 'Xem CSSD - Báo cáo'),
  ('CSSD_REPORT', 'export', 'Xuất dữ liệu CSSD - Báo cáo'),
  ('CSSD_KHO_DUNGCU', 'view', 'Xem CSSD - Kho Dụng cụ'),
  ('CSSD_KHO_DUNGCU', 'create', 'Thêm CSSD - Kho Dụng cụ'),
  ('CSSD_KHO_DUNGCU', 'edit', 'Sửa CSSD - Kho Dụng cụ'),
  ('CSSD_KHO_DUNGCU', 'delete', 'Xóa CSSD - Kho Dụng cụ'),
  ('CSSD_KHO_DUNGCU', 'import', 'Import CSSD - Kho Dụng cụ'),
  ('CSSD_WORKFLOW', 'view', 'Xem CSSD - Quy trình (Luân chuyển QR)'),
  ('CSSD_WORKFLOW', 'create', 'Thêm CSSD - Quy trình (Luân chuyển QR)'),
  ('CSSD_WORKFLOW', 'edit', 'Sửa CSSD - Quy trình (Luân chuyển QR)'),
  ('CSSD_WORKFLOW', 'delete', 'Xóa CSSD - Quy trình (Luân chuyển QR)'),
  ('CSSD_ME_TIET_KHUAN', 'view', 'Xem CSSD - Mẻ Tiệt khuẩn'),
  ('CSSD_ME_TIET_KHUAN', 'create', 'Thêm CSSD - Mẻ Tiệt khuẩn'),
  ('CSSD_ME_TIET_KHUAN', 'edit', 'Sửa CSSD - Mẻ Tiệt khuẩn'),
  ('CSSD_ME_TIET_KHUAN', 'delete', 'Xóa CSSD - Mẻ Tiệt khuẩn'),
  ('CSSD_ME_TIET_KHUAN', 'import', 'Import CSSD - Mẻ Tiệt khuẩn'),
  ('CSSD_ME_TIET_KHUAN', 'qc', 'Kiểm định chất lượng CSSD - Mẻ Tiệt khuẩn'),
  ('CSSD_ME_TIET_KHUAN', 'lock', 'Khóa an toàn CSSD - Mẻ Tiệt khuẩn'),
  ('KSNK_KHO_HOACHAT', 'view', 'Xem KSNK - Kho hóa chất / vật tư'),
  ('KSNK_KHO_HOACHAT', 'create', 'Thêm KSNK - Kho hóa chất / vật tư'),
  ('KSNK_KHO_HOACHAT', 'edit', 'Sửa KSNK - Kho hóa chất / vật tư'),
  ('KSNK_KHO_HOACHAT', 'export', 'Xuất dữ liệu KSNK - Kho hóa chất / vật tư'),
  ('GIAM_SAT_VST', 'view', 'Xem Giám sát Vệ sinh tay'),
  ('GIAM_SAT_VST', 'create', 'Thêm Giám sát Vệ sinh tay'),
  ('GIAM_SAT_VST', 'edit', 'Sửa Giám sát Vệ sinh tay'),
  ('GIAM_SAT_VST', 'delete', 'Xóa Giám sát Vệ sinh tay'),
  ('GIAM_SAT_VST', 'import', 'Import Giám sát Vệ sinh tay'),
  ('GIAM_SAT_CHUNG', 'view', 'Xem Giám sát Bảng kiểm chung'),
  ('GIAM_SAT_CHUNG', 'create', 'Thêm Giám sát Bảng kiểm chung'),
  ('GIAM_SAT_CHUNG', 'edit', 'Sửa Giám sát Bảng kiểm chung'),
  ('GIAM_SAT_CHUNG', 'delete', 'Xóa Giám sát Bảng kiểm chung'),
  ('GIAM_SAT_CHUNG', 'import', 'Import Giám sát Bảng kiểm chung'),
  ('GIAM_SAT_NKBV', 'view', 'Xem Giám sát Nhiễm khuẩn BV (NKBV / HAI)'),
  ('GIAM_SAT_NKBV', 'create', 'Thêm Giám sát Nhiễm khuẩn BV (NKBV / HAI)'),
  ('GIAM_SAT_NKBV', 'edit', 'Sửa Giám sát Nhiễm khuẩn BV (NKBV / HAI)'),
  ('GIAM_SAT_NKBV', 'delete', 'Xóa Giám sát Nhiễm khuẩn BV (NKBV / HAI)'),
  ('GIAM_SAT_NKBV', 'import', 'Import Giám sát Nhiễm khuẩn BV (NKBV / HAI)'),
  ('PHAN_QUYEN', 'view', 'Xem Quản trị Phân quyền'),
  ('PHAN_QUYEN', 'create', 'Thêm Quản trị Phân quyền'),
  ('PHAN_QUYEN', 'edit', 'Sửa Quản trị Phân quyền'),
  ('PHAN_QUYEN', 'delete', 'Xóa Quản trị Phân quyền'),
  ('BAO_SU_CO', 'view', 'Xem Báo cáo Sự cố'),
  ('BAO_SU_CO', 'create', 'Thêm Báo cáo Sự cố')
ON CONFLICT (module_name, action) DO UPDATE SET
  description = EXCLUDED.description;

-- ADMIN: full permission matrix
INSERT INTO public.sys_role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM public.sys_roles r
CROSS JOIN public.sys_permissions p
WHERE r.name = 'ADMIN'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- NHAN_VIEN_KSNK: operational subset (view/create/edit/delete/import on supervision + CSSD + core MDM views)
INSERT INTO public.sys_role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM public.sys_roles r
JOIN public.sys_permissions p ON true
WHERE r.name = 'NHAN_VIEN_KSNK'
  AND (
    (p.module_name IN ('GIAM_SAT_VST','GIAM_SAT_CHUNG','GIAM_SAT_NKBV','CONG_VIEC','BAO_SU_CO')
     AND p.action IN ('view','create','edit','delete','import'))
    OR (p.module_name LIKE 'DASHBOARD%' AND p.action IN ('view','export'))
    OR (p.module_name IN ('CSSD_WORKFLOW','CSSD_KHO_DUNGCU','CSSD_REPORT','CSSD_ME_TIET_KHUAN','KSNK_KHO_HOACHAT')
        AND p.action IN ('view','create','edit','delete','import','qc','lock','export'))
    OR (p.module_name IN ('NHAN_SU','BANG_KIEM','DANH_MUC') AND p.action IN ('view','create','edit','delete','import'))
    OR (p.module_name = 'PHAN_QUYEN' AND p.action = 'view')
    OR (p.module_name IN ('LOAI_DC','BO_DC','DC_LE','THIET_BI','HOA_CHAT','KHOA_PHONG','BANG_KIEM_DETAIL') AND p.action = 'view')
  )
ON CONFLICT (role_id, permission_id) DO NOTHING;

COMMIT;
