-- Pilot nhân sự + auth local — generated by scripts/generate-pilot-seeds.ts
-- Password mặc định local: Pilot@103 (đổi sau khi đăng nhập)
-- Chỉ dùng môi trường local/dev — KHÔNG push credential lên staging/prod.

BEGIN;

-- Khoa KSNK pilot
INSERT INTO public.mdm_dm_khoa_phong (id, ma_khoa, ten_khoa, is_active, created_at, updated_at)
VALUES (
  'aaaaaaaa-bbbb-cccc-dddd-000000000001',
  'KSNK',
  'Khoa Kiểm soát Nhiễm khuẩn',
  true,
  now(),
  now()
)
ON CONFLICT (id) DO UPDATE SET
  ma_khoa = EXCLUDED.ma_khoa,
  ten_khoa = EXCLUDED.ten_khoa,
  is_active = EXCLUDED.is_active,
  updated_at = now();

-- Auth user (Supabase local)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  raw_app_meta_data,
  raw_user_meta_data,
  created_at,
  updated_at,
  confirmation_token,
  email_change,
  email_change_token_new,
  recovery_token
)
VALUES (
  '00000000-0000-0000-0000-000000000000',
  'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbb001',
  'authenticated',
  'authenticated',
  'ksnkbv103@gmail.com',
  extensions.crypt('Pilot@103', extensions.gen_salt('bf')),
  now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  '{"full_name":"Quản trị viên KSNK Pilot"}'::jsonb,
  now(),
  now(),
  '',
  '',
  '',
  ''
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
)
SELECT
  'cccccccc-cccc-cccc-cccc-cccccccc0001',
  'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbb001',
  jsonb_build_object(
    'sub', 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbb001',
    'email', 'ksnkbv103@gmail.com',
    'email_verified', true
  ),
  'email',
  'ksnkbv103@gmail.com',
  now(),
  now(),
  now()
WHERE NOT EXISTS (
  SELECT 1 FROM auth.identities
  WHERE provider = 'email' AND provider_id = 'ksnkbv103@gmail.com'
);

-- Hồ sơ nhân sự
INSERT INTO public.mdm_nhan_su (
  id,
  ho_ten,
  ma_nv,
  khoa_id,
  is_active,
  auth_user_id,
  extra_data,
  created_at,
  updated_at
)
VALUES (
  'dddddddd-dddd-dddd-dddd-dddddddddd01',
  'Quản trị viên KSNK Pilot',
  'ADMIN01',
  'aaaaaaaa-bbbb-cccc-dddd-000000000001',
  true,
  'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbb001',
  '{"email":"ksnkbv103@gmail.com"}'::jsonb,
  now(),
  now()
)
ON CONFLICT (id) DO UPDATE SET
  ho_ten = EXCLUDED.ho_ten,
  ma_nv = EXCLUDED.ma_nv,
  khoa_id = EXCLUDED.khoa_id,
  is_active = EXCLUDED.is_active,
  auth_user_id = EXCLUDED.auth_user_id,
  extra_data = EXCLUDED.extra_data,
  updated_at = now();

-- Gán role ADMIN
INSERT INTO public.sys_user_roles (user_id, role_id)
SELECT
  'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbb001',
  r.id
FROM public.sys_roles r
WHERE r.name = 'ADMIN'
ON CONFLICT (user_id, role_id) DO NOTHING;

COMMIT;
