/**
 * Generates supabase/seeds/00-rbac.sql and 01-pilot-nhan-su.sql from permission registry.
 * Run: npx tsx scripts/generate-pilot-seeds.ts
 */
import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import { getFlatPermissions } from "../src/lib/permission-registry";
import { KSNK_RBAC_ROLE_NAMES } from "../src/modules/quan-tri-he-thong/phan-quyen/actions/rbac-ksnk-role-mappings";

const OUT_DIR = join(process.cwd(), "supabase/seeds");

const ROLE_DESCRIPTIONS: Record<string, string> = {
  ADMIN: "Quản trị hệ thống (Root)",
  NHAN_VIEN_KSNK: "Nhân viên khoa Kiểm soát nhiễm khuẩn",
  HOI_DONG_KSNK: "Hội đồng KSNK — chủ yếu xem báo cáo",
  MANG_LUOI_KSNK: "Mạng lưới KSNK (vai trò hệ thống)",
  TO_TRUONG_MANG_LUOI_KSNK: "Tổ trưởng tổ mạng lưới KSNK theo khoa",
  THANH_VIEN_MANG_LUOI_KSNK: "Thành viên mạng lưới KSNK theo khoa",
  BAN_QLCL: "Ban Quản lý Chất lượng Bệnh viện — tiếp nhận ticket RCA hệ thống",
  KHOA_TRANG_BI: "Khoa Trang bị — tiếp nhận ticket RCA về thiết bị/nguồn lực",
};

function sqlEscape(s: string) {
  return s.replace(/'/g, "''");
}

function buildRbacSql() {
  const perms = getFlatPermissions();
  const roleNames = ["ADMIN", ...KSNK_RBAC_ROLE_NAMES];

  const roleInserts = roleNames
    .map(
      (name) =>
        `  ('${name}', '${sqlEscape(ROLE_DESCRIPTIONS[name] || name)}', true)`,
    )
    .join(",\n");

  const permInserts = perms
    .map(
      (p) =>
        `  ('${sqlEscape(p.module_name)}', '${sqlEscape(p.action)}', '${sqlEscape(p.description)}')`,
    )
    .join(",\n");

  return `-- Pilot RBAC seed — generated by scripts/generate-pilot-seeds.ts
-- Idempotent: safe to re-run after supabase db reset --local

BEGIN;

INSERT INTO public.sys_roles (name, description, is_active)
VALUES
${roleInserts}
ON CONFLICT (name) DO UPDATE SET
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active,
  updated_at = now();

INSERT INTO public.sys_permissions (module_name, action, description)
VALUES
${permInserts}
ON CONFLICT (module_name, action) DO UPDATE SET
  description = EXCLUDED.description;

-- ADMIN: full permission matrix
INSERT INTO public.sys_role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM public.sys_roles r
CROSS JOIN public.sys_permissions p
WHERE r.name = 'ADMIN'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- NHAN_VIEN_KSNK: operational subset (view/create/edit/delete/import on supervision + CSSD + core MDM views)
INSERT INTO public.sys_role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM public.sys_roles r
JOIN public.sys_permissions p ON true
WHERE r.name = 'NHAN_VIEN_KSNK'
  AND (
    (p.module_name IN ('GIAM_SAT_VST','GIAM_SAT_CHUNG','GIAM_SAT_NKBV','CONG_VIEC','BAO_SU_CO')
     AND p.action IN ('view','create','edit','delete','import'))
    OR (p.module_name LIKE 'DASHBOARD%' AND p.action IN ('view','export'))
    OR (p.module_name IN ('CSSD_WORKFLOW','CSSD_KHO_DUNGCU','CSSD_REPORT','CSSD_ME_TIET_KHUAN','KSNK_KHO_HOACHAT')
        AND p.action IN ('view','create','edit','delete','import','qc','lock','export'))
    OR (p.module_name IN ('NHAN_SU','BANG_KIEM','DANH_MUC') AND p.action IN ('view','create','edit','delete','import'))
    OR (p.module_name = 'PHAN_QUYEN' AND p.action = 'view')
    OR (p.module_name IN ('LOAI_DC','BO_DC','DC_LE','THIET_BI','HOA_CHAT','KHOA_PHONG','BANG_KIEM_DETAIL') AND p.action = 'view')
  )
ON CONFLICT (role_id, permission_id) DO NOTHING;

COMMIT;
`;
}

function buildPilotNhanSuSql() {
  return `-- Pilot nhân sự + auth local — generated by scripts/generate-pilot-seeds.ts
-- Password mặc định local: Pilot@103 (đổi sau khi đăng nhập)
-- Chỉ dùng môi trường local/dev — KHÔNG push credential lên staging/prod.

BEGIN;

-- Khoa KSNK pilot
INSERT INTO public.mdm_dm_khoa_phong (id, ma_khoa, ten_khoa, is_active, created_at, updated_at)
VALUES (
  'aaaaaaaa-bbbb-cccc-dddd-000000000001',
  'KSNK',
  'Khoa Kiểm soát Nhiễm khuẩn',
  true,
  now(),
  now()
)
ON CONFLICT (id) DO UPDATE SET
  ma_khoa = EXCLUDED.ma_khoa,
  ten_khoa = EXCLUDED.ten_khoa,
  is_active = EXCLUDED.is_active,
  updated_at = now();

-- Auth user (Supabase local)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  raw_app_meta_data,
  raw_user_meta_data,
  created_at,
  updated_at,
  confirmation_token,
  email_change,
  email_change_token_new,
  recovery_token
)
VALUES (
  '00000000-0000-0000-0000-000000000000',
  'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbb001',
  'authenticated',
  'authenticated',
  'ksnkbv103@gmail.com',
  extensions.crypt('Pilot@103', extensions.gen_salt('bf')),
  now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  '{"full_name":"Quản trị viên KSNK Pilot"}'::jsonb,
  now(),
  now(),
  '',
  '',
  '',
  ''
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
)
SELECT
  'cccccccc-cccc-cccc-cccc-cccccccc0001',
  'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbb001',
  jsonb_build_object(
    'sub', 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbb001',
    'email', 'ksnkbv103@gmail.com',
    'email_verified', true
  ),
  'email',
  'ksnkbv103@gmail.com',
  now(),
  now(),
  now()
WHERE NOT EXISTS (
  SELECT 1 FROM auth.identities
  WHERE provider = 'email' AND provider_id = 'ksnkbv103@gmail.com'
);

-- Hồ sơ nhân sự
INSERT INTO public.mdm_nhan_su (
  id,
  ho_ten,
  ma_nv,
  khoa_id,
  is_active,
  auth_user_id,
  extra_data,
  created_at,
  updated_at
)
VALUES (
  'dddddddd-dddd-dddd-dddd-dddddddddd01',
  'Quản trị viên KSNK Pilot',
  'ADMIN01',
  'aaaaaaaa-bbbb-cccc-dddd-000000000001',
  true,
  'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbb001',
  '{"email":"ksnkbv103@gmail.com"}'::jsonb,
  now(),
  now()
)
ON CONFLICT (id) DO UPDATE SET
  ho_ten = EXCLUDED.ho_ten,
  ma_nv = EXCLUDED.ma_nv,
  khoa_id = EXCLUDED.khoa_id,
  is_active = EXCLUDED.is_active,
  auth_user_id = EXCLUDED.auth_user_id,
  extra_data = EXCLUDED.extra_data,
  updated_at = now();

-- Gán role ADMIN
INSERT INTO public.sys_user_roles (user_id, role_id)
SELECT
  'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbb001',
  r.id
FROM public.sys_roles r
WHERE r.name = 'ADMIN'
ON CONFLICT (user_id, role_id) DO NOTHING;

COMMIT;
`;
}

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(join(OUT_DIR, "00-rbac.sql"), buildRbacSql(), "utf8");
writeFileSync(join(OUT_DIR, "01-pilot-nhan-su.sql"), buildPilotNhanSuSql(), "utf8");
console.log("Wrote supabase/seeds/00-rbac.sql and 01-pilot-nhan-su.sql");
