-- EXPLAIN — Dashboard hybrid (Command Center + module tabs) sau reform 2026-05-30.
-- Cửa sổ ~3 tháng lịch (khớp BV103_ANALYTICS_DEFAULT_MONTHS / bv103-analytics-default-range.ts).
-- Chạy trên staging/pilot; ANALYZE ghi thật — tránh prod cao tải.
--
-- SSOT từng RPC (một statement/file — Supabase `db query` không gộp multi-cmd):
--   scripts/sql/pilot-dashboard-explain/*.sql
-- Chạy: npm run pilot:dashboard:explain:linked  |  :local
