-- 20260528000003_gstt_act_and_form_seed.sql
-- Generated by scripts/parse-giamsat-markdown-forms.mjs
-- Forms parsed: 8, unique reasons: 0
begin;

-- 1. ACT catalog (ghi nhận only — metadata.chi_ghi_nhan=true)
insert into public.sys_lookup_value (category_type, code, name, is_active, metadata)
values ('HANH_DONG_CAN_THIEP', 'ACT-100', 'Nhắc nhở và hướng dẫn lại tại chỗ (Coaching)', true, '{"chi_ghi_nhan":true}'::jsonb)
on conflict (category_type, code) do update set name = excluded.name, is_active = true, metadata = excluded.metadata;
insert into public.sys_lookup_value (category_type, code, name, is_active, metadata)
values ('HANH_DONG_CAN_THIEP', 'ACT-200', 'Yêu cầu khắc phục/làm lại ngay lập tức', true, '{"chi_ghi_nhan":true}'::jsonb)
on conflict (category_type, code) do update set name = excluded.name, is_active = true, metadata = excluded.metadata;
insert into public.sys_lookup_value (category_type, code, name, is_active, metadata)
values ('HANH_DONG_CAN_THIEP', 'ACT-300', 'Đề xuất cấp phát và bổ sung phương tiện/vật tư', true, '{"chi_ghi_nhan":true}'::jsonb)
on conflict (category_type, code) do update set name = excluded.name, is_active = true, metadata = excluded.metadata;
insert into public.sys_lookup_value (category_type, code, name, is_active, metadata)
values ('HANH_DONG_CAN_THIEP', 'ACT-400', 'Đình chỉ/Dừng hoạt động (Stop the line)', true, '{"chi_ghi_nhan":true}'::jsonb)
on conflict (category_type, code) do update set name = excluded.name, is_active = true, metadata = excluded.metadata;
insert into public.sys_lookup_value (category_type, code, name, is_active, metadata)
values ('HANH_DONG_CAN_THIEP', 'ACT-500', 'Lập biên bản và báo cáo sự cố an toàn', true, '{"chi_ghi_nhan":true}'::jsonb)
on conflict (category_type, code) do update set name = excluded.name, is_active = true, metadata = excluded.metadata;

-- 2. Nguyên nhân lỗi JCI → sys_lookup_value (ghi nhận / Pareto — không workflow)
insert into public.sys_lookup_value (category_type, code, name, description, is_active, metadata) values
('NGUYEN_NHAN_LOI','101_SYS','Thiếu vật tư, trang thiết bị tại điểm chăm sóc','Không có sẵn dung dịch VST, hết găng tay, thiếu hộp kháng thủng.',true,'{"nhom_loi":"HE_THONG","ma_jci":"101-SYS"}'::jsonb),
('NGUYEN_NHAN_LOI','102_SYS','Thiết kế môi trường/Công thái học bất hợp lý','Vị trí bồn rửa tay/bình cồn quá xa, bị che khuất.',true,'{"nhom_loi":"HE_THONG","ma_jci":"102-SYS"}'::jsonb),
('NGUYEN_NHAN_LOI','103_SYS','Quá tải công việc / Phân bổ nhân sự chưa phù hợp','Áp lực thời gian khiến NVYT không đủ thời gian thực hiện đúng quy trình.',true,'{"nhom_loi":"HE_THONG","ma_jci":"103-SYS"}'::jsonb),
('NGUYEN_NHAN_LOI','104_SYS','Lỗi thiết bị kỹ thuật / Hỏng hóc máy móc','Máy tiệt khuẩn hỏng, vòi nước hỏng, hệ thống lọc khí không đạt chuẩn.',true,'{"nhom_loi":"HE_THONG","ma_jci":"104-SYS"}'::jsonb),
('NGUYEN_NHAN_LOI','105_SYS','Lỗ hổng quy trình / Thiếu y lệnh','Không có hướng dẫn rõ ràng, thiếu y lệnh lâm sàng cho các can thiệp KSNK.',true,'{"nhom_loi":"HE_THONG","ma_jci":"105-SYS"}'::jsonb),
('NGUYEN_NHAN_LOI','106_SYS','Lỗi hệ thống thông tin / Giao tiếp và bàn giao kém','Không cảnh báo MDROs khi chuyển khoa, lỗi giao tiếp trong kíp trực.',true,'{"nhom_loi":"HE_THONG","ma_jci":"106-SYS"}'::jsonb),
('NGUYEN_NHAN_LOI','201_HUM','Yếu tố Kỹ năng / Đào tạo chưa đạt','Thực hiện sai kỹ thuật chuyên môn do thiếu kiến thức hoặc chưa được giám sát đúng mức.',true,'{"nhom_loi":"CON_NGUOI","ma_jci":"201-HUM"}'::jsonb),
('NGUYEN_NHAN_LOI','202_HUM','Hành vi rủi ro - Nhận thức sai lệch','Lạm dụng găng tay thay vì vệ sinh tay do nhận thức sai.',true,'{"nhom_loi":"CON_NGUOI","ma_jci":"202-HUM"}'::jsonb),
('NGUYEN_NHAN_LOI','203_HUM','Hành vi rủi ro - Thói quen đi tắt (Workaround)','Bỏ qua các bước kiểm tra an toàn để làm nhanh hơn.',true,'{"nhom_loi":"CON_NGUOI","ma_jci":"203-HUM"}'::jsonb),
('NGUYEN_NHAN_LOI','204_HUM','Yếu tố Tâm sinh lý / Trạng thái cá nhân','Quên, mất tập trung, nhầm lẫn do mệt mỏi (lỗi vô ý).',true,'{"nhom_loi":"CON_NGUOI","ma_jci":"204-HUM"}'::jsonb),
('NGUYEN_NHAN_LOI','205_HUM','Hành vi liều lĩnh (Reckless behavior)','Cố tình vi phạm quy định an toàn cốt lõi dù đã biết rủi ro.',true,'{"nhom_loi":"CON_NGUOI","ma_jci":"205-HUM"}'::jsonb),
('NGUYEN_NHAN_LOI','206_HUM','Lỗi thao tác vận hành do quy trình phức tạp','Thao tác sai do độ phức tạp của thiết bị vượt quá khả năng xử lý.',true,'{"nhom_loi":"CON_NGUOI","ma_jci":"206-HUM"}'::jsonb),
('NGUYEN_NHAN_LOI','207_HUM','Yếu tố Sức khỏe nghề nghiệp','Viêm da tiếp xúc, dị ứng hóa chất, nứt nẻ tay cản trở thực hành.',true,'{"nhom_loi":"CON_NGUOI","ma_jci":"207-HUM"}'::jsonb),
('NGUYEN_NHAN_LOI','301_CLI','Tình huống cấp cứu khẩn cấp','Tình huống đe dọa tính mạng khiến tuân thủ KSNK bị gián đoạn.',true,'{"nhom_loi":"LAM_SANG","ma_jci":"301-CLI"}'::jsonb),
('NGUYEN_NHAN_LOI','302_CLI','Yếu tố tâm lý / Hành vi của người bệnh','NB kích thích, vật vã, mê sảng, không hợp tác.',true,'{"nhom_loi":"LAM_SANG","ma_jci":"302-CLI"}'::jsonb),
('NGUYEN_NHAN_LOI','304_CLI','Tình trạng giải phẫu / Bệnh lý đặc thù','Khó khăn khách quan từ cơ địa NB cản trở thao tác vô khuẩn.',true,'{"nhom_loi":"LAM_SANG","ma_jci":"304-CLI"}'::jsonb)
on conflict (category_type, code) do update set
  name = excluded.name,
  description = excluded.description,
  metadata = excluded.metadata,
  is_active = true;

-- 3. Schema
alter table public.gstt_dm_bang_kiem add column if not exists hanh_dong_khac_phuc_jsonb jsonb not null default '[]'::jsonb;
alter table public.gstt_fact_chung_sessions add column if not exists phieu_phan_tich_jsonb jsonb not null default '{}'::jsonb;
comment on column public.gstt_dm_bang_kiem.hanh_dong_khac_phuc_jsonb is 'Phần 4 mẫu: [{stt, noi_dung, action_code, la_stop_the_line}]';
comment on column public.gstt_fact_chung_sessions.phieu_phan_tich_jsonb is 'Phần 3+4 phiên: nguyen_nhan + hanh_dong snapshot (ghi nhận, không workflow)';

-- 4. Per-template allowlist + hành động (resolve lookup id by code)
update public.gstt_dm_bang_kiem bk set
  hanh_dong_khac_phuc_jsonb = $jsonb$[]$jsonb$::jsonb,
  nguyen_nhan_cho_phep_jsonb = coalesce(
    (select jsonb_agg(
      jsonb_build_object(
        'lookup_id', l.id::text,
        'lookup_code', l.code,
        'ten_hien_thi', coalesce(e->>'ten_hien_thi', l.name),
        'mo_ta_chi_tiet', coalesce(e->>'mo_ta_chi_tiet', l.description),
        'thu_tu_hien_thi', (e->>'thu_tu_hien_thi')::int
      ) order by (e->>'thu_tu_hien_thi')::int
    ) from jsonb_array_elements($jsonb$[]$jsonb$::jsonb) e
    join public.sys_lookup_value l on l.category_type = 'NGUYEN_NHAN_LOI' and l.code = e->>'lookup_code'),
    '[]'::jsonb)
where bk.ma_bk = 'BM.03.03';

update public.gstt_dm_bang_kiem bk set
  hanh_dong_khac_phuc_jsonb = $jsonb$[]$jsonb$::jsonb,
  nguyen_nhan_cho_phep_jsonb = coalesce(
    (select jsonb_agg(
      jsonb_build_object(
        'lookup_id', l.id::text,
        'lookup_code', l.code,
        'ten_hien_thi', coalesce(e->>'ten_hien_thi', l.name),
        'mo_ta_chi_tiet', coalesce(e->>'mo_ta_chi_tiet', l.description),
        'thu_tu_hien_thi', (e->>'thu_tu_hien_thi')::int
      ) order by (e->>'thu_tu_hien_thi')::int
    ) from jsonb_array_elements($jsonb$[]$jsonb$::jsonb) e
    join public.sys_lookup_value l on l.category_type = 'NGUYEN_NHAN_LOI' and l.code = e->>'lookup_code'),
    '[]'::jsonb)
where bk.ma_bk = 'BM.07.03';

update public.gstt_dm_bang_kiem bk set
  hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"* [ ] CẢNH BÁO KHẨN CẤP: Chặn ngay lập tức hành vi dùng 2 tay đậy nắp kim, tháo/bẻ kim hoặc cắm kim lưu trên lọ thuốc của NVYT.","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"* [ ] Yêu cầu NVYT thải bỏ ngay vật sắc nhọn đang để tạm trên khay hạt đậu/giường bệnh vào hộp kháng thủng màu vàng.","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"* [ ] Đề xuất thay thế ngay Hộp kháng thủng mới (nếu hộp hiện tại đã đầy vượt vạch 3/4) hoặc bổ sung ngay nếu không có sẵn trên xe tiêm.","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"* [ ] Yêu cầu NVYT sát khuẩn lại da/nắp lọ và bắt buộc chờ cồn khô hoàn toàn trước khi tiếp tục thủ thuật chọc kim.","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"* [ ] Kích hoạt khẩn cấp Quy trình Xử lý phơi nhiễm nghề nghiệp (QT.KSNK.10) nếu quan sát thấy NVYT vừa bị kim đâm/quẹt rách da.","action_code":"ACT-200","la_stop_the_line":false}]$jsonb$::jsonb,
  nguyen_nhan_cho_phep_jsonb = coalesce(
    (select jsonb_agg(
      jsonb_build_object(
        'lookup_id', l.id::text,
        'lookup_code', l.code,
        'ten_hien_thi', coalesce(e->>'ten_hien_thi', l.name),
        'mo_ta_chi_tiet', coalesce(e->>'mo_ta_chi_tiet', l.description),
        'thu_tu_hien_thi', (e->>'thu_tu_hien_thi')::int
      ) order by (e->>'thu_tu_hien_thi')::int
    ) from jsonb_array_elements($jsonb$[]$jsonb$::jsonb) e
    join public.sys_lookup_value l on l.category_type = 'NGUYEN_NHAN_LOI' and l.code = e->>'lookup_code'),
    '[]'::jsonb)
where bk.ma_bk = 'BM.09.01';

update public.gstt_dm_bang_kiem bk set
  hanh_dong_khac_phuc_jsonb = $jsonb$[]$jsonb$::jsonb,
  nguyen_nhan_cho_phep_jsonb = coalesce(
    (select jsonb_agg(
      jsonb_build_object(
        'lookup_id', l.id::text,
        'lookup_code', l.code,
        'ten_hien_thi', coalesce(e->>'ten_hien_thi', l.name),
        'mo_ta_chi_tiet', coalesce(e->>'mo_ta_chi_tiet', l.description),
        'thu_tu_hien_thi', (e->>'thu_tu_hien_thi')::int
      ) order by (e->>'thu_tu_hien_thi')::int
    ) from jsonb_array_elements($jsonb$[]$jsonb$::jsonb) e
    join public.sys_lookup_value l on l.category_type = 'NGUYEN_NHAN_LOI' and l.code = e->>'lookup_code'),
    '[]'::jsonb)
where bk.ma_bk = 'BM.15.01';

update public.gstt_dm_bang_kiem bk set
  hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"* [ ] Đình chỉ và Yêu cầu làm lại: Trả lại ngay dụng cụ bẩn (còn sót vết máu, mảng bám, chưa khô) để ngâm Enzyme và cọ rửa lại từ đầu.","action_code":"ACT-400","la_stop_the_line":true},{"stt":2,"noi_dung":"* [ ] Cảnh báo và chấn chỉnh ngay lập tức hành vi cọ rửa dụng cụ trên mặt nước, yêu cầu nhân viên dìm ngập tay và dụng cụ dưới nước để bảo vệ hô hấp và niêm mạc.","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"* [ ] Yêu cầu NVYT mang bổ sung ngay kính bảo hộ/tấm che mặt và tạp dề chống thấm trước khi tiếp tục công việc tại khu bẩn CSSD.","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"* [ ] Phản hồi trực tiếp cho ĐD Trưởng khoa lâm sàng/Phòng mổ nếu phát hiện bộ dụng cụ bị ngâm sai quy định trong dung dịch NaCl 0.9% hoặc để khô két máu.","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"* [ ] Cấp phát bổ sung khẩn cấp các loại chổi cọ nòng phù hợp với kích thước lỗ (lumen) của ống hút/trocar.","action_code":"ACT-300","la_stop_the_line":false}]$jsonb$::jsonb,
  nguyen_nhan_cho_phep_jsonb = coalesce(
    (select jsonb_agg(
      jsonb_build_object(
        'lookup_id', l.id::text,
        'lookup_code', l.code,
        'ten_hien_thi', coalesce(e->>'ten_hien_thi', l.name),
        'mo_ta_chi_tiet', coalesce(e->>'mo_ta_chi_tiet', l.description),
        'thu_tu_hien_thi', (e->>'thu_tu_hien_thi')::int
      ) order by (e->>'thu_tu_hien_thi')::int
    ) from jsonb_array_elements($jsonb$[]$jsonb$::jsonb) e
    join public.sys_lookup_value l on l.category_type = 'NGUYEN_NHAN_LOI' and l.code = e->>'lookup_code'),
    '[]'::jsonb)
where bk.ma_bk = 'BM.18.02';

update public.gstt_dm_bang_kiem bk set
  hanh_dong_khac_phuc_jsonb = $jsonb$[]$jsonb$::jsonb,
  nguyen_nhan_cho_phep_jsonb = coalesce(
    (select jsonb_agg(
      jsonb_build_object(
        'lookup_id', l.id::text,
        'lookup_code', l.code,
        'ten_hien_thi', coalesce(e->>'ten_hien_thi', l.name),
        'mo_ta_chi_tiet', coalesce(e->>'mo_ta_chi_tiet', l.description),
        'thu_tu_hien_thi', (e->>'thu_tu_hien_thi')::int
      ) order by (e->>'thu_tu_hien_thi')::int
    ) from jsonb_array_elements($jsonb$[]$jsonb$::jsonb) e
    join public.sys_lookup_value l on l.category_type = 'NGUYEN_NHAN_LOI' and l.code = e->>'lookup_code'),
    '[]'::jsonb)
where bk.ma_bk = 'BM.20.02';

update public.gstt_dm_bang_kiem bk set
  hanh_dong_khac_phuc_jsonb = $jsonb$[]$jsonb$::jsonb,
  nguyen_nhan_cho_phep_jsonb = coalesce(
    (select jsonb_agg(
      jsonb_build_object(
        'lookup_id', l.id::text,
        'lookup_code', l.code,
        'ten_hien_thi', coalesce(e->>'ten_hien_thi', l.name),
        'mo_ta_chi_tiet', coalesce(e->>'mo_ta_chi_tiet', l.description),
        'thu_tu_hien_thi', (e->>'thu_tu_hien_thi')::int
      ) order by (e->>'thu_tu_hien_thi')::int
    ) from jsonb_array_elements($jsonb$[]$jsonb$::jsonb) e
    join public.sys_lookup_value l on l.category_type = 'NGUYEN_NHAN_LOI' and l.code = e->>'lookup_code'),
    '[]'::jsonb)
where bk.ma_bk = 'BM.21.04';

update public.gstt_dm_bang_kiem bk set
  hanh_dong_khac_phuc_jsonb = $jsonb$[]$jsonb$::jsonb,
  nguyen_nhan_cho_phep_jsonb = coalesce(
    (select jsonb_agg(
      jsonb_build_object(
        'lookup_id', l.id::text,
        'lookup_code', l.code,
        'ten_hien_thi', coalesce(e->>'ten_hien_thi', l.name),
        'mo_ta_chi_tiet', coalesce(e->>'mo_ta_chi_tiet', l.description),
        'thu_tu_hien_thi', (e->>'thu_tu_hien_thi')::int
      ) order by (e->>'thu_tu_hien_thi')::int
    ) from jsonb_array_elements($jsonb$[]$jsonb$::jsonb) e
    join public.sys_lookup_value l on l.category_type = 'NGUYEN_NHAN_LOI' and l.code = e->>'lookup_code'),
    '[]'::jsonb)
where bk.ma_bk = 'BM.QĐ.09.01';

-- 5. Allowlist mặc định (bảng TUAN_THU chưa có) — 12 mã phổ biến
with default_reasons as (
  select coalesce(jsonb_agg(
    jsonb_build_object(
      'lookup_id', l.id::text,
      'lookup_code', l.code,
      'ten_hien_thi', l.name,
      'mo_ta_chi_tiet', l.description,
      'thu_tu_hien_thi', r.ord
    ) order by r.ord
  ), '[]'::jsonb) as payload
  from (
    select l.*, row_number() over (order by l.code) as ord
    from public.sys_lookup_value l
    where l.category_type = 'NGUYEN_NHAN_LOI'
      and l.is_active = true
      and l.code in (
        '101_SYS','102_SYS','103_SYS','201_HUM','203_HUM','204_HUM',
        '205_HUM','301_CLI','302_CLI','104_SYS','105_SYS','206_HUM'
      )
  ) r
  join public.sys_lookup_value l on l.id = r.id
)
update public.gstt_dm_bang_kiem bk
set nguyen_nhan_cho_phep_jsonb = (select payload from default_reasons)
where bk.loai_giam_sat = 'TUAN_THU'
  and coalesce(jsonb_array_length(bk.nguyen_nhan_cho_phep_jsonb), 0) = 0;

-- 6. Hành động mặc định từ catalog ACT
with default_acts as (
  select coalesce(jsonb_agg(
    jsonb_build_object(
      'stt', a.ord,
      'noi_dung', a.name,
      'action_code', a.code,
      'la_stop_the_line', a.code = 'ACT-400'
    ) order by a.ord
  ), '[]'::jsonb) as payload
  from (
    select l.code, l.name, row_number() over (order by l.code) as ord
    from public.sys_lookup_value l
    where l.category_type = 'HANH_DONG_CAN_THIEP' and l.is_active = true
  ) a
)
update public.gstt_dm_bang_kiem bk
set hanh_dong_khac_phuc_jsonb = (select payload from default_acts)
where bk.loai_giam_sat = 'TUAN_THU'
  and coalesce(jsonb_array_length(bk.hanh_dong_khac_phuc_jsonb), 0) = 0;

commit;