-- 20260528000013_gstt_act_headlines_shorter.sql
-- Rút gọn đầu mục biện pháp can thiệp (~48 ký tự), giữ đủ số dòng từ seed gốc
begin;

-- BM.03.03: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Yêu cầu nhà thầu dán niêm phong lại ngay lập…","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu thay ngay thảm dính bụi mới tại lối…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu nhà thầu dùng khăn ẩm hoặc máy hút…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Mời ngay công nhân ra khỏi khu vực thi công…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ thi công ngay lập tức","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.03.03';

-- BM.07.02: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Nhắc nhở và hướng dẫn lại tại chỗ (Coaching)…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Hướng dẫn lại kỹ thuật lau khô tay và dùng…","action_code":"ACT-100","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu nhân viên y tế tháo bỏ ngay lập tức…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu thực hiện lại thao tác vệ sinh tay…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Ghi nhận tình trạng viêm da cơ địa (nếu có)…","action_code":"ACT-200","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.07.02';

-- BM.07.03: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Nhắc nhở và chấn chỉnh ngay tư thế (yêu cầu…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Hướng dẫn lại tại chỗ (Coaching) kỹ thuật sử…","action_code":"ACT-100","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu tháo bỏ ngay nhẫn","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu NVYT chờ cồn sát khuẩn bay hơi","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ thao tác mang găng/mặc áo vô khuẩn","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.07.03';

-- BM.08.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Hướng dẫn lại tại chỗ (Coaching) kỹ thuật…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Cảnh báo và yêu cầu NVYT tháo găng tay","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu NVYT thay ngay PPE mới và vệ sinh…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Đặt/Bổ sung thùng rác lây nhiễm (màu Vàng)…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Báo cáo Điều dưỡng trưởng / Bộ phận hậu cần…","action_code":"ACT-300","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.08.01';

-- BM.09.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"CẢNH BÁO KHẨN CẤP","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu NVYT thải bỏ ngay vật sắc nhọn đang…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Đề xuất thay thế ngay Hộp kháng thủng mới…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu NVYT sát khuẩn lại da/nắp lọ và bắt…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Kích hoạt khẩn cấp Quy trình Xử lý phơi…","action_code":"ACT-200","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.09.01';

-- BM.10.01: 6 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Cảnh báo và yêu cầu NVYT dừng ngay mọi thao…","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Can thiệp lập tức nếu phát hiện NVYT đang…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Cung cấp ngay dung dịch NaCl 0.9% để rửa…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Hỗ trợ NVYT gọi ngay số điện thoại Hotline…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Phân công NVYT khác trong ca trực tiếp tục…","action_code":"ACT-200","la_stop_the_line":false},{"stt":6,"noi_dung":"Hướng dẫn Điều dưỡng trưởng khoa/NVYT hoàn…","action_code":"ACT-500","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.10.01';

-- BM.14.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Trực tiếp nhắc nhở","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu NVYT quay lại vùng đệm/ngoài cửa…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Chặn ngay lập tức và yêu cầu NVYT tháo bỏ PTPH","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu dán ngay Biển báo cách ly…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Yêu cầu Khoa tiến hành khử khuẩn ngay các…","action_code":"ACT-200","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.14.01';

-- BM.31.03: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Giải thích","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu NVYT lập tức quay lại cửa phòng/vùng…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu dán ngay \"Biển báo phòng ngừa lây…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Báo cáo Điều dưỡng trưởng / Bộ phận hậu cần…","action_code":"ACT-300","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ ngay việc sử dụng ống nghe/nhiệt kế…","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.31.03';

-- BM.17.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"\"Người giám sát\" lập tức can thiệp","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Thiết lập ngay hàng rào vật lý","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Cung cấp ngay lập tức bộ PTPH đúng chuẩn (áo…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Hướng dẫn phong tỏa khu vực có tràn đổ…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.17.01';

-- BM.15.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Nhắc nhở khoa giao cần gọi điện báo trước…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu NVYT quay lại lau khử khuẩn toàn bộ…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Hủy bỏ và thay mới ngay tấm trải/ga giường…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu Khoa giao cấp phát và hướng dẫn…","action_code":"ACT-300","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ hành vi rủi ro","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.15.01';

-- BM.16.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Hướng dẫn lại (Coaching) kỹ thuật sử dụng…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Điều động/Nhắc nhở Hộ lý/NVVS thực hiện Vệ…","action_code":"ACT-100","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu Điều dưỡng/Nhân viên nhà tang lễ…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu thực hiện lồng thêm túi thứ hai…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Yêu cầu dán bổ sung Nhãn \"Cảnh báo lây nhiễm…","action_code":"ACT-200","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.16.01';

-- BM.18.02: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Cảnh báo và chấn chỉnh ngay lập tức hành vi…","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu NVYT mang bổ sung ngay kính bảo…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Phản hồi trực tiếp cho ĐD Trưởng khoa lâm…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Cấp phát bổ sung khẩn cấp các loại chổi cọ…","action_code":"ACT-300","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ và Yêu cầu làm lại","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.18.02';

-- BM.19.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Nhắc nhở và yêu cầu NVYT mang bổ sung ngay…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Bắt buộc đổ bỏ và thay mới chậu hóa chất…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu nhân viên làm lại quy trình từ bước…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Kích hoạt quy trình thu hồi dụng cụ (Recall)…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ quy trình","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.19.01';

-- BM.19.02: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Hướng dẫn lại tại chỗ (Coaching) cách sử…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu trả lại ngay dụng cụ về khu bẩn (để…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Ghi nhận tình trạng dụng cụ hỏng vào sổ giao…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Đình chỉ đóng gói","action_code":"ACT-400","la_stop_the_line":true},{"stt":5,"noi_dung":"Cung cấp và bổ sung ngay chất bôi trơn dụng…","action_code":"ACT-500","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.19.02';

-- BM.20.02: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Yêu cầu cắt bỏ đường hàn","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu mở gói và bổ sung ngay Chỉ thị hóa…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu nhân viên tháo và mở tất cả các chốt…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Báo cáo cho bộ phận bảo trì để tiến hành…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ thao tác đóng gói và gửi dụng cụ…","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.20.02';

-- BM.22.04: 6 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Thu hồi khẩn cấp (Recall)","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu nhân viên dỡ lại mẻ hấp","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu đẩy xe dụng cụ vào lại khu vực lưu…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu nhân viên vận hành ký tên","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ máy ngay lập tức","action_code":"ACT-400","la_stop_the_line":true},{"stt":6,"noi_dung":"Cảnh báo và đình chỉ xuất xưởng nếu phát…","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.22.04';

-- BM.QĐ.19.03: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Yêu cầu loại bỏ ngay vào thùng rác các vật…","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu nhân viên CSSD hủy bỏ ngay lập tức…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu Điều dưỡng trưởng sắp xếp lại tủ vật…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Đình chỉ và Tịch thu","action_code":"ACT-400","la_stop_the_line":true},{"stt":5,"noi_dung":"Kích hoạt quy trình thu hồi (Recall) và báo…","action_code":"ACT-500","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.QĐ.19.03';

-- BM.21.04: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Hướng dẫn lại tại chỗ (Coaching) cho nhân…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu nhân viên sắp xếp lại ngay lập tức…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu lau khô hoàn toàn mặt bàn/mâm khay…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Báo cáo Khoa Trang bị / Hậu cần kỹ thuật…","action_code":"ACT-300","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ sử dụng & Thu hồi","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.21.04';

-- BM.25.01: 4 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Yêu cầu Bác sĩ thay ngay găng tay vô khuẩn…","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu Điều dưỡng phụ khẩn cấp đội mũ trùm…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Ghi chú cảnh báo vào hồ sơ bệnh án","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Đình chỉ thủ thuật","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.25.01';

-- BM.25.03: 10 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Nhắc nhở và yêu cầu Bác sĩ bổ sung ngay đánh…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu Điều dưỡng/Hộ lý xả ngay túi nước…","action_code":"ACT-100","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu chuẩn bị dụng cụ và thay ngay băng…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu tháo bỏ và thay mới hệ thống dây…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Cảnh báo NVYT về việc vệ sinh tay ngay lập…","action_code":"ACT-200","la_stop_the_line":false},{"stt":6,"noi_dung":"Cảnh báo và yêu cầu treo ngay túi dẫn lưu…","action_code":"ACT-200","la_stop_the_line":false},{"stt":7,"noi_dung":"Cung cấp ngay bình đong nước tiểu sạch","action_code":"ACT-200","la_stop_the_line":false},{"stt":8,"noi_dung":"Phản hồi trực tiếp yêu cầu Bác sĩ ghi bổ…","action_code":"ACT-200","la_stop_the_line":false},{"stt":9,"noi_dung":"Đình chỉ thao tác","action_code":"ACT-400","la_stop_the_line":true},{"stt":10,"noi_dung":"Đình chỉ thao tác và nhắc nhở nghiêm khắc…","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.25.03';

-- BM.27.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Hướng dẫn lại tại chỗ (Coaching) cách dán…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Phản hồi trực tiếp với Bác sĩ điều trị để…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu thực hiện vệ sinh tay lại ngay lập…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu treo ngay túi dẫn lưu thấp hơn bàng…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ thủ thuật","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.27.01';

-- BM.27.02: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Yêu cầu Điều dưỡng/Hộ lý xả ngay túi nước…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Cảnh báo và yêu cầu treo ngay túi dẫn lưu…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Cung cấp ngay bình đong nước tiểu sạch","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Phản hồi trực tiếp yêu cầu Bác sĩ ghi bổ…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ thao tác và nhắc nhở nghiêm khắc…","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.27.02';

-- BM.26.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Hướng dẫn lại tại chỗ (Coaching) kỹ thuật đổ…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Nhắc nhở trực tiếp và yêu cầu Bác sĩ bổ sung…","action_code":"ACT-100","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu Điều dưỡng lập tức điều chỉnh nâng…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu NVYT lấy bàn chải mềm thực hiện lại…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Bổ sung khẩn cấp bộ dụng cụ chăm sóc răng miệng","action_code":"ACT-300","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.26.01';

-- BM.24.02: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Nhắc nhở Bác sĩ Gây mê/Điều dưỡng kiểm tra…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu người không có nhiệm vụ ra ngoài và…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu Điều dưỡng tại khoa Hồi sức/Ngoại…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Đình chỉ thủ thuật","action_code":"ACT-400","la_stop_the_line":true},{"stt":5,"noi_dung":"Đình chỉ ngay việc sử dụng dao cạo lông vũ…","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.24.02';

-- BM.11.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Cảnh báo và yêu cầu đổi ngay xô/giẻ lau nếu…","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu đổ bỏ dung dịch hóa chất và pha lại…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Trực tiếp yêu cầu nhân viên vệ sinh/điều…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu nhân viên vệ sinh lập tức đặt biển…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ thao tác quét khô trong buồng bệnh","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.11.01';

-- BM.QĐ.12.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Nhắc nhở và yêu cầu Điều dưỡng/Người nhà Vệ…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu nhân viên lấy khăn ẩm thấm nước sạch…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu đổ bỏ ngay nước trong bình làm ẩm và…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Cung cấp bút và nhãn dán","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ ngay lập tức","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.QĐ.12.01';

-- BM.QĐ.20.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Nhắc nhở và yêu cầu Điều dưỡng/Bác sĩ nha…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu thực hiện quy trình khử khuẩn sốc…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu Kỹ sư/Điều dưỡng hoàn thiện ngay…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Đình chỉ hệ thống ngay lập tức","action_code":"ACT-400","la_stop_the_line":true},{"stt":5,"noi_dung":"Đình chỉ thao tác phẫu thuật nha khoa","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.QĐ.20.01';

-- BM.13.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Nhắc nhở và yêu cầu dừng ngay lập tức hành…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu phân loại lại tại chỗ nếu phát hiện…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu dùng tấm nilon/vải sạch che đậy kín…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Dừng vận hành máy giặt và báo cáo khoa Trang…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Lập biên bản báo cáo sự cố an toàn (Incident…","action_code":"ACT-500","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.13.01';

-- BM.12.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Cảnh báo và yêu cầu nhân viên y tế/vệ sinh…","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Cung cấp ngay hộp kháng thủng thay thế và…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Tạm dừng xe vận chuyển rác nếu phát hiện xe…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Đình chỉ thao tác thu gom và yêu cầu Nhân…","action_code":"ACT-400","la_stop_the_line":true},{"stt":5,"noi_dung":"Báo cáo Trưởng khoa và lập biên bản sự cố…","action_code":"ACT-500","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.12.01';

-- BM.QĐ.08.01: 6 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Nhắc nhở người bệnh/người nhà và lập tức…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Hướng dẫn lại tại chỗ (Coaching) cho NVYT…","action_code":"ACT-100","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu Điều dưỡng phụ trách ca trực thực…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Báo cáo khẩn cấp cho phòng Hành chính Quản…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"*le*−2.5 Pa) hoặc quạt hút không hoạt động.","action_code":"ACT-200","la_stop_the_line":false},{"stt":6,"noi_dung":"Treo biển \"Phòng lỗi - Không sử dụng\" và…","action_code":"ACT-200","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.QĐ.08.01';

-- BM.QĐ.02.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Yêu cầu người không có nhiệm vụ ra ngoài","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Báo cáo ngay cho Đơn vị Kỹ thuật/Bảo trì nếu…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu điều dưỡng đổi bộ dụng cụ khác ngay…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Đình chỉ thao tác","action_code":"ACT-400","la_stop_the_line":true},{"stt":5,"noi_dung":"Đình chỉ việc sử dụng dao cạo lông vũ","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.QĐ.02.01';

-- BM.QĐ.03.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Cảnh báo và yêu cầu Kỹ thuật viên hình ảnh…","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu nhân viên y tế lấy áo chì đang bị…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Cung cấp ngay khăn tẩm cồn/hóa chất và yêu…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu đóng kín cửa phòng Cathlab và mời…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ thủ thuật","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.QĐ.03.01';

-- BM.QĐ.09.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Yêu cầu đóng kín cửa phòng bệnh ngay lập tức…","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Mời ngay khách thăm hoặc người nhà ra khỏi…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu NVYT quay lại khu vực phòng đệm để…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu nhân viên vệ sinh tiến hành lau ẩm…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ và Tịch thu","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.QĐ.09.01';

-- BM.QĐ.17.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Nhắc nhở và hướng dẫn lại tại chỗ (Coaching)…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu Dược sĩ/NVYT ra ngoài phòng đệm để…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu tiêu hủy ngay lập tức túi dịch hoặc…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu NVYT lấy gạc tẩm Cồn 70° lau sát…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ hệ thống","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.QĐ.17.01';

-- BM.QĐ.16.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Nhắc nhở và yêu cầu bổ sung ngay kính bảo…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu di chuyển ngay các mẫu bệnh phẩm…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Cảnh báo và yêu cầu nhân viên tháo găng","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Phong tỏa tạm thời khu vực và hướng dẫn nhân…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ và yêu cầu nhân viên y tế lập tức…","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.QĐ.16.01';

-- BM.QĐ.18.02: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Yêu cầu nhân viên tháo bỏ trang sức","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu sắp xếp lại ngay tủ bảo quản thực…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu nhân viên lấy mẫu bổ sung ngay lập…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Đình chỉ và Tiêu hủy","action_code":"ACT-400","la_stop_the_line":true},{"stt":5,"noi_dung":"Đình chỉ công việc tại bếp ngay lập tức đối…","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.QĐ.18.02';

commit;

-- 36 forms · 187 action headlines