-- 20260528000012_gstt_restore_act_headlines.sql
-- Khôi phục đầy đủ biện pháp can thiệp: đầu mục ngắn + mã ACT (từ seed gốc part34 + backfill 4 mẫu)
begin;

-- BM.03.03: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Yêu cầu nhà thầu dán niêm phong lại ngay lập tức các khe hở, mép nối r…","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu thay ngay thảm dính bụi mới tại lối ra vào nếu thảm cũ đã bám…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu nhà thầu dùng khăn ẩm hoặc máy hút bụi có màng lọc HEPA làm sạ…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Mời ngay công nhân ra khỏi khu vực thi công nếu phát hiện có hành vi h…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ thi công ngay lập tức","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.03.03';

-- BM.07.02: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Nhắc nhở và hướng dẫn lại tại chỗ (Coaching) đúng trình tự kỹ thuật vệ…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Hướng dẫn lại kỹ thuật lau khô tay và dùng giấy lót để khóa vòi nước n…","action_code":"ACT-100","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu nhân viên y tế tháo bỏ ngay lập tức trang sức (nhẫn, đồng hồ)…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu thực hiện lại thao tác vệ sinh tay ngay lập tức trước khi chạm…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Ghi nhận tình trạng viêm da cơ địa (nếu có) và tư vấn/đề xuất chuyển đ…","action_code":"ACT-200","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.07.02';

-- BM.07.03: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Nhắc nhở và chấn chỉnh ngay tư thế (yêu cầu NVYT nâng bàn tay cao hơn…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Hướng dẫn lại tại chỗ (Coaching) kỹ thuật sử dụng khăn lau vô khuẩn từ…","action_code":"ACT-100","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu tháo bỏ ngay nhẫn, đồng hồ, vòng tay trước khi tiếp tục quá tr…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu NVYT chờ cồn sát khuẩn bay hơi, tay khô tự nhiên hoàn toàn trư…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ thao tác mang găng/mặc áo vô khuẩn, yêu cầu NVYT quay lại bồn…","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.07.03';

-- BM.08.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Hướng dẫn lại tại chỗ (Coaching) kỹ thuật cởi PPE an toàn, cuộn mặt bẩ…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Cảnh báo và yêu cầu NVYT tháo găng tay, thực hiện vệ sinh tay ngay lập…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu NVYT thay ngay PPE mới và vệ sinh tay nếu phát hiện găng tay/á…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Đặt/Bổ sung thùng rác lây nhiễm (màu Vàng) tại khu vực tháo bỏ PPE nga…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Báo cáo Điều dưỡng trưởng / Bộ phận hậu cần bổ sung khẩn cấp xe PPE (K…","action_code":"ACT-300","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.08.01';

-- BM.09.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"CẢNH BÁO KHẨN CẤP","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu NVYT thải bỏ ngay vật sắc nhọn đang để tạm trên khay hạt đậu/g…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Đề xuất thay thế ngay Hộp kháng thủng mới (nếu hộp hiện tại đã đầy vượ…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu NVYT sát khuẩn lại da/nắp lọ và bắt buộc chờ cồn khô hoàn toàn…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Kích hoạt khẩn cấp Quy trình Xử lý phơi nhiễm nghề nghiệp (QT.KSNK.10)…","action_code":"ACT-200","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.09.01';

-- BM.10.01: 6 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Cảnh báo và yêu cầu NVYT dừng ngay mọi thao tác chăm sóc/điều trị đối…","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Can thiệp lập tức nếu phát hiện NVYT đang nặn/bóp máu","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Cung cấp ngay dung dịch NaCl 0.9% để rửa mắt/niêm mạc (Nếu là tai nạn văng bắn dịch)","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Hỗ trợ NVYT gọi ngay số điện thoại Hotline Khoa Truyền nhiễm/KSNK để n…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Phân công NVYT khác trong ca trực tiếp tục thực hiện phần công việc đa…","action_code":"ACT-200","la_stop_the_line":false},{"stt":6,"noi_dung":"Hướng dẫn Điều dưỡng trưởng khoa/NVYT hoàn thành \"Biên bản báo cáo tai…","action_code":"ACT-500","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.10.01';

-- BM.14.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Trực tiếp nhắc nhở, giải thích và yêu cầu NB/người nhà đóng kín cửa ph…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu NVYT quay lại vùng đệm/ngoài cửa phòng để mang ĐÚNG và ĐỦ PTPH…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Chặn ngay lập tức và yêu cầu NVYT tháo bỏ PTPH, vệ sinh tay nếu phát h…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu dán ngay Biển báo cách ly (Vàng/Cam/Xanh) ngoài cửa phòng; bố…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Yêu cầu Khoa tiến hành khử khuẩn ngay các thiết bị y tế (ống nghe, huy…","action_code":"ACT-200","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.14.01';

-- BM.31.03: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Giải thích, nhắc nhở nghiêm khắc đối với người nhà/khách thăm về việc…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu NVYT lập tức quay lại cửa phòng/vùng đệm để mang đủ Áo choàng…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu dán ngay \"Biển báo phòng ngừa lây qua tiếp xúc\" (Màu vàng) trư…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Báo cáo Điều dưỡng trưởng / Bộ phận hậu cần bổ sung khẩn cấp xe PTPH (…","action_code":"ACT-300","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ ngay việc sử dụng ống nghe/nhiệt kế chung; yêu cầu tiến hành…","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.31.03';

-- BM.17.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"\"Người giám sát\" lập tức can thiệp, yêu cầu NVYT dừng thao tác, thực h…","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Thiết lập ngay hàng rào vật lý, dán băng keo phân định rõ 3 vùng (Sạch…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Cung cấp ngay lập tức bộ PTPH đúng chuẩn (áo chống thấm, tấm che mặt,…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Hướng dẫn phong tỏa khu vực có tràn đổ máu/dịch tiết (chất nôn, máu) v…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.17.01';

-- BM.15.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Nhắc nhở khoa giao cần gọi điện báo trước tình trạng cách ly của bệnh…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu NVYT quay lại lau khử khuẩn toàn bộ các bề mặt tiếp xúc của xe…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Hủy bỏ và thay mới ngay tấm trải/ga giường trên xe/cáng nếu phát hiện…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu Khoa giao cấp phát và hướng dẫn người bệnh (có triệu chứng hô…","action_code":"ACT-300","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ hành vi rủi ro","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.15.01';

-- BM.16.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Hướng dẫn lại (Coaching) kỹ thuật sử dụng bông/gạc chèn kín các lỗ tự…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Điều động/Nhắc nhở Hộ lý/NVVS thực hiện Vệ sinh bề mặt bước cuối đối v…","action_code":"ACT-100","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu Điều dưỡng/Nhân viên nhà tang lễ mang đầy đủ PTPH (đặc biệt là…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu thực hiện lồng thêm túi thứ hai (Đóng gói kép) ngay tại chỗ nế…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Yêu cầu dán bổ sung Nhãn \"Cảnh báo lây nhiễm nguy hiểm\" lên mặt ngoài…","action_code":"ACT-200","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.16.01';

-- BM.18.02: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Cảnh báo và chấn chỉnh ngay lập tức hành vi cọ rửa dụng cụ trên mặt nư…","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu NVYT mang bổ sung ngay kính bảo hộ/tấm che mặt và tạp dề chống…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Phản hồi trực tiếp cho ĐD Trưởng khoa lâm sàng/Phòng mổ nếu phát hiện…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Cấp phát bổ sung khẩn cấp các loại chổi cọ nòng phù hợp với kích thước…","action_code":"ACT-300","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ và Yêu cầu làm lại","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.18.02';

-- BM.19.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Nhắc nhở và yêu cầu NVYT mang bổ sung ngay PTPH (tạp dề chống thấm, gă…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Bắt buộc đổ bỏ và thay mới chậu hóa chất KKMĐC nếu kiểm tra nồng độ bằ…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu nhân viên làm lại quy trình từ bước cọ rửa bằng Enzyme nếu phá…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Kích hoạt quy trình thu hồi dụng cụ (Recall) nếu phát hiện thiết bị đã…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ quy trình","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.19.01';

-- BM.19.02: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Hướng dẫn lại tại chỗ (Coaching) cách sử dụng kính lúp để soi khe kẽ,…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu trả lại ngay dụng cụ về khu bẩn (để rửa lại từ đầu) nếu phát h…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Ghi nhận tình trạng dụng cụ hỏng vào sổ giao nhận/phần mềm quản lý tài…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Đình chỉ đóng gói, yêu cầu loại bỏ và thay thế ngay dụng cụ bị rỉ sét,…","action_code":"ACT-400","la_stop_the_line":true},{"stt":5,"noi_dung":"Cung cấp và bổ sung ngay chất bôi trơn dụng cụ y tế chuyên dụng (thu h…","action_code":"ACT-500","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.19.02';

-- BM.20.02: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Yêu cầu cắt bỏ đường hàn, thay túi mới và hàn lại ngay lập tức nếu phá…","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu mở gói và bổ sung ngay Chỉ thị hóa học (CI) nội bộ vào tâm gói…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu nhân viên tháo và mở tất cả các chốt khóa panh/kéo, đồng thời…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Báo cáo cho bộ phận bảo trì để tiến hành điều chỉnh thông số hoặc sửa…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ thao tác đóng gói và gửi dụng cụ quay lại khu bẩn để ngâm enz…","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.20.02';

-- BM.22.04: 6 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Thu hồi khẩn cấp (Recall)","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu nhân viên dỡ lại mẻ hấp, sắp xếp lại vào các giá đỡ (rack) nếu…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu đẩy xe dụng cụ vào lại khu vực lưu lưu chờ, nghiêm cấm dỡ đồ k…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu nhân viên vận hành ký tên, dán biểu đồ nhiệt và hoàn thiện hồ…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ máy ngay lập tức","action_code":"ACT-400","la_stop_the_line":true},{"stt":6,"noi_dung":"Cảnh báo và đình chỉ xuất xưởng nếu phát hiện nhân viên CSSD định giao…","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.22.04';

-- BM.QĐ.19.03: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Yêu cầu loại bỏ ngay vào thùng rác các vật tư dùng 1 lần đã được mang…","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu nhân viên CSSD hủy bỏ ngay lập tức các SUDs không có tên trong…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu Điều dưỡng trưởng sắp xếp lại tủ vật tư theo nguyên tắc FEFO/F…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Đình chỉ và Tịch thu","action_code":"ACT-400","la_stop_the_line":true},{"stt":5,"noi_dung":"Kích hoạt quy trình thu hồi (Recall) và báo cáo sự cố y khoa nếu phát…","action_code":"ACT-500","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.QĐ.19.03';

-- BM.21.04: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Hướng dẫn lại tại chỗ (Coaching) cho nhân viên về 4 yếu tố bắt buộc ph…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu nhân viên sắp xếp lại ngay lập tức giá kệ tủ nếu phát hiện tìn…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu lau khô hoàn toàn mặt bàn/mâm khay tại khoa lâm sàng trước khi…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Báo cáo Khoa Trang bị / Hậu cần kỹ thuật khẩn cấp để sửa chữa nếu ghi…","action_code":"ACT-300","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ sử dụng & Thu hồi","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.21.04';

-- BM.25.01: 4 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Yêu cầu Bác sĩ thay ngay găng tay vô khuẩn mới hoặc thay săng trải bàn…","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu Điều dưỡng phụ khẩn cấp đội mũ trùm tóc và mang khẩu trang y t…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Ghi chú cảnh báo vào hồ sơ bệnh án","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Đình chỉ thủ thuật","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.25.01';

-- BM.25.03: 10 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Nhắc nhở và yêu cầu Bác sĩ bổ sung ngay đánh giá y lệnh Rút hoặc Tiếp…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu Điều dưỡng/Hộ lý xả ngay túi nước tiểu nếu quan sát thấy túi đ…","action_code":"ACT-100","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu chuẩn bị dụng cụ và thay ngay băng dán CVC mới với kỹ thuật vô…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu tháo bỏ và thay mới hệ thống dây truyền dịch, chạc ba ngay lập…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Cảnh báo NVYT về việc vệ sinh tay ngay lập tức nếu họ vừa tiếp xúc với…","action_code":"ACT-200","la_stop_the_line":false},{"stt":6,"noi_dung":"Cảnh báo và yêu cầu treo ngay túi dẫn lưu THẤP HƠN bàng quang và móc c…","action_code":"ACT-200","la_stop_the_line":false},{"stt":7,"noi_dung":"Cung cấp ngay bình đong nước tiểu sạch, có dán tên/số giường riêng biệ…","action_code":"ACT-200","la_stop_the_line":false},{"stt":8,"noi_dung":"Phản hồi trực tiếp yêu cầu Bác sĩ ghi bổ sung y lệnh đánh giá Rút hoặc…","action_code":"ACT-200","la_stop_the_line":false},{"stt":9,"noi_dung":"Đình chỉ thao tác","action_code":"ACT-400","la_stop_the_line":true},{"stt":10,"noi_dung":"Đình chỉ thao tác và nhắc nhở nghiêm khắc nếu phát hiện Điều dưỡng cố…","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.25.03';

-- BM.27.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Hướng dẫn lại tại chỗ (Coaching) cách dán băng dính cố định ống thông…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Phản hồi trực tiếp với Bác sĩ điều trị để xem xét/hủy y lệnh nếu phát…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu thực hiện vệ sinh tay lại ngay lập tức nếu phát hiện nhân viên…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu treo ngay túi dẫn lưu thấp hơn bàng quang, đảm bảo hệ thống dẫ…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ thủ thuật","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.27.01';

-- BM.27.02: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Yêu cầu Điều dưỡng/Hộ lý xả ngay túi nước tiểu nếu quan sát thấy túi đ…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Cảnh báo và yêu cầu treo ngay túi dẫn lưu THẤP HƠN bàng quang và móc c…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Cung cấp ngay bình đong nước tiểu sạch, có dán tên/số giường riêng biệ…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Phản hồi trực tiếp yêu cầu Bác sĩ ghi bổ sung y lệnh đánh giá Rút hoặc…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ thao tác và nhắc nhở nghiêm khắc nếu phát hiện Điều dưỡng cố…","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.27.02';

-- BM.26.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Hướng dẫn lại tại chỗ (Coaching) kỹ thuật đổ nước đọng trong bẫy nước…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Nhắc nhở trực tiếp và yêu cầu Bác sĩ bổ sung y lệnh đánh giá Thử nghiệ…","action_code":"ACT-100","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu Điều dưỡng lập tức điều chỉnh nâng đầu giường đạt $30^\\circ -…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu NVYT lấy bàn chải mềm thực hiện lại thao tác vệ sinh răng miện…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Bổ sung khẩn cấp bộ dụng cụ chăm sóc răng miệng, ống hút đờm kín hoặc…","action_code":"ACT-300","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.26.01';

-- BM.24.02: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Nhắc nhở Bác sĩ Gây mê/Điều dưỡng kiểm tra và bổ sung liều Kháng sinh…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu người không có nhiệm vụ ra ngoài và đóng kín ngay cửa phòng mổ…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu Điều dưỡng tại khoa Hồi sức/Ngoại khoa thay ngay đôi găng tay…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Đình chỉ thủ thuật","action_code":"ACT-400","la_stop_the_line":true},{"stt":5,"noi_dung":"Đình chỉ ngay việc sử dụng dao cạo lông vũ để dọn lông vùng mổ; yêu cầ…","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.24.02';

-- BM.11.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Cảnh báo và yêu cầu đổi ngay xô/giẻ lau nếu phát hiện nhân viên đang s…","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu đổ bỏ dung dịch hóa chất và pha lại ngay lập tức nếu kiểm tra…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Trực tiếp yêu cầu nhân viên vệ sinh/điều dưỡng lau lại các bề mặt tiếp…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu nhân viên vệ sinh lập tức đặt biển cảnh báo \"Sàn ướt/Trơn trượ…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ thao tác quét khô trong buồng bệnh, yêu cầu nhân viên đổi san…","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.11.01';

-- BM.QĐ.12.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Nhắc nhở và yêu cầu Điều dưỡng/Người nhà Vệ sinh tay (cồn) ngay lập tứ…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu nhân viên lấy khăn ẩm thấm nước sạch lau/tráng lại toàn bộ bề…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu đổ bỏ ngay nước trong bình làm ẩm và thay bằng nước vô khuẩn n…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Cung cấp bút và nhãn dán, yêu cầu nhân viên ghi và dán ngay nhãn \"Đã v…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ ngay lập tức","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.QĐ.12.01';

-- BM.QĐ.20.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Nhắc nhở và yêu cầu Điều dưỡng/Bác sĩ nha khoa thực hiện bấm xả đường…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu thực hiện quy trình khử khuẩn sốc (Shock treatment) cho đường…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu Kỹ sư/Điều dưỡng hoàn thiện ngay việc ghi chép và ký xác nhận…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Đình chỉ hệ thống ngay lập tức","action_code":"ACT-400","la_stop_the_line":true},{"stt":5,"noi_dung":"Đình chỉ thao tác phẫu thuật nha khoa, yêu cầu Bác sĩ chuyển ngay sang…","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.QĐ.20.01';

-- BM.13.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Nhắc nhở và yêu cầu dừng ngay lập tức hành vi giũ, tung đồ vải bẩn tro…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu phân loại lại tại chỗ nếu phát hiện đồ vải lây nhiễm bị bỏ nhầ…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu dùng tấm nilon/vải sạch che đậy kín ngay lập tức xe chở đồ vải…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Dừng vận hành máy giặt và báo cáo khoa Trang thiết bị/Kỹ thuật nếu đồn…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Lập biên bản báo cáo sự cố an toàn (Incident Report) nếu nhân viên giặ…","action_code":"ACT-500","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.13.01';

-- BM.12.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Cảnh báo và yêu cầu nhân viên y tế/vệ sinh nhặt lại bằng kẹp/găng tay…","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Cung cấp ngay hộp kháng thủng thay thế và yêu cầu đóng chốt khóa an to…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Tạm dừng xe vận chuyển rác nếu phát hiện xe không có nắp đậy hoặc đang…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Đình chỉ thao tác thu gom và yêu cầu Nhân viên vệ sinh mang ngay găng…","action_code":"ACT-400","la_stop_the_line":true},{"stt":5,"noi_dung":"Báo cáo Trưởng khoa và lập biên bản sự cố cận kề (Near-miss) ngay lập…","action_code":"ACT-500","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.12.01';

-- BM.QĐ.08.01: 6 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Nhắc nhở người bệnh/người nhà và lập tức đóng kín cửa phòng AIIR nếu p…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Hướng dẫn lại tại chỗ (Coaching) cho NVYT cách sử dụng dải ruy băng/th…","action_code":"ACT-100","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu Điều dưỡng phụ trách ca trực thực hiện kiểm tra trực quan và g…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Báo cáo khẩn cấp cho phòng Hành chính Quản trị/Kỹ thuật nếu đồng hồ đo…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"*le*−2.5 Pa) hoặc quạt hút không hoạt động","action_code":"ACT-200","la_stop_the_line":false},{"stt":6,"noi_dung":"Treo biển \"Phòng lỗi - Không sử dụng\" và tiến hành di chuyển người bện…","action_code":"ACT-200","la_stop_the_line":false}]$jsonb$::jsonb where ma_bk = 'BM.QĐ.08.01';

-- BM.QĐ.02.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Yêu cầu người không có nhiệm vụ ra ngoài, đóng kín cửa phòng mổ ngay l…","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Báo cáo ngay cho Đơn vị Kỹ thuật/Bảo trì nếu hệ thống thông khí, nhiệt…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu điều dưỡng đổi bộ dụng cụ khác ngay lập tức nếu hộp dụng cụ kh…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Đình chỉ thao tác, yêu cầu NVYT tháo bỏ trang sức, rửa tay lại và thay…","action_code":"ACT-400","la_stop_the_line":true},{"stt":5,"noi_dung":"Đình chỉ việc sử dụng dao cạo lông vũ, yêu cầu đổi sang dùng tông đơ đ…","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.QĐ.02.01';

-- BM.QĐ.03.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Cảnh báo và yêu cầu Kỹ thuật viên hình ảnh lùi lại, thay mới ngay tấm…","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu nhân viên y tế lấy áo chì đang bị vứt/gấp trên ghế treo ngay l…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Cung cấp ngay khăn tẩm cồn/hóa chất và yêu cầu Điều dưỡng lau sạch vết…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu đóng kín cửa phòng Cathlab và mời những người không có nhiệm v…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ thủ thuật","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.QĐ.03.01';

-- BM.QĐ.09.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Yêu cầu đóng kín cửa phòng bệnh ngay lập tức và kiểm tra lại đồng hồ/l…","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Mời ngay khách thăm hoặc người nhà ra khỏi khu vực PE nếu phát hiện có…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu NVYT quay lại khu vực phòng đệm để thực hiện vệ sinh tay và ma…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu nhân viên vệ sinh tiến hành lau ẩm khử khuẩn lại ngay lập tức…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ và Tịch thu","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.QĐ.09.01';

-- BM.QĐ.17.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Nhắc nhở và hướng dẫn lại tại chỗ (Coaching) về vị trí đặt tay, sắp xế…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu Dược sĩ/NVYT ra ngoài phòng đệm để tháo bỏ trang sức, rửa tay…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu tiêu hủy ngay lập tức túi dịch hoặc sản phẩm đang pha chế nếu…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Yêu cầu NVYT lấy gạc tẩm Cồn 70° lau sát khuẩn lại toàn bộ bề mặt vật…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ hệ thống","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.QĐ.17.01';

-- BM.QĐ.16.01: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Nhắc nhở và yêu cầu bổ sung ngay kính bảo hộ/tấm che mặt trước khi Kỹ…","action_code":"ACT-100","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu di chuyển ngay các mẫu bệnh phẩm đang xử lý dở dang (có nguy c…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Cảnh báo và yêu cầu nhân viên tháo găng, vệ sinh tay ngay lập tức nếu…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Phong tỏa tạm thời khu vực và hướng dẫn nhân viên sử dụng Bộ xử lý trà…","action_code":"ACT-200","la_stop_the_line":false},{"stt":5,"noi_dung":"Đình chỉ và yêu cầu nhân viên y tế lập tức cởi bỏ áo choàng labo/găng…","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.QĐ.16.01';

-- BM.QĐ.18.02: 5 đầu mục
update public.gstt_dm_bang_kiem set hanh_dong_khac_phuc_jsonb = $jsonb$[{"stt":1,"noi_dung":"Yêu cầu nhân viên tháo bỏ trang sức, đi rửa tay bằng xà phòng và mang…","action_code":"ACT-200","la_stop_the_line":false},{"stt":2,"noi_dung":"Yêu cầu sắp xếp lại ngay tủ bảo quản thực phẩm theo đúng nguyên tắc \"C…","action_code":"ACT-200","la_stop_the_line":false},{"stt":3,"noi_dung":"Yêu cầu nhân viên lấy mẫu bổ sung ngay lập tức và hoàn thiện chữ ký và…","action_code":"ACT-200","la_stop_the_line":false},{"stt":4,"noi_dung":"Đình chỉ và Tiêu hủy","action_code":"ACT-400","la_stop_the_line":true},{"stt":5,"noi_dung":"Đình chỉ công việc tại bếp ngay lập tức đối với nhân viên đang có biểu…","action_code":"ACT-400","la_stop_the_line":true}]$jsonb$::jsonb where ma_bk = 'BM.QĐ.18.02';

commit;

-- 36 forms · 187 action headlines